version: '3.1'
services:
  postgres:
    image: postgres:9.6
    container_name: postgres
    network_mode: 'host'
    ports:
      - '5432:5432'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: q1w2e3
      POSTGRES_DB: gobarber

  mongo:
    image: mongo:4.0
    restart: always
    container_name: mongo
    ports:
      - '27017:27017'

  redis:
    image: redis:alpine
    restart: always
    container_name: redis
    ports:
      - '6379:6379'
